# Generated by Django 4.2.27 on 2026-01-13 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='telefone',
            field=models.CharField(default='75-98805-4564', max_length=14, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99)99999-9999', regex='^\\(\\d{2}\\)\\d{5}-\\d{4}$')]),
            preserve_default=False,
        ),
    ]
