# Generated by Django 4.2.27 on 2026-01-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editoras', '0002_alter_editora_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
