# Generated by Django 4.2.27 on 2026-01-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editoras', '0002_alter_editora_telefone'),
        ('livros', '0003_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editoras.editora', verbose_name='Editora'),
        ),
    ]
