# Generated by Django 4.2.27 on 2026-01-15 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
        ('livros', '0004_alter_livro_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autores.autor', verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
