# Generated by Django 4.2.27 on 2026-01-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_livro_autor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
    ]
